version: "3.9"
services:
  rpn:
    build: .
    command: flask --debug run
    ports:
      - "8080:5000"
    volumes:
      - ./project:/usr/local/share/rpn
  redis:
    image: "redis:7.0-alpine"
    volumes:
      - redis-data:/data
volumes:
  redis-data: